{% from "dockers/dockerfile-macros.j2" import install_debian_packages %}
FROM docker-config-engine-buster

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

## Pre-install the fundamental packages
RUN apt-get update \
 && apt-get -y install  \
    gdb                 \
    libboost-atomic1.71.0

COPY \
{% for deb in docker_saiserver_bfn_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
debs/

RUN apt-get install -y \
        libxml2 \
        libpcap-dev \
        libusb-1.0-0-dev \
        libcurl4 \
        libcurl4-gnutls-dev \
        libunwind8-dev \
        libpython3.4 \
        libc-ares2 \
        libgoogle-perftools4

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_saiserver_bfn_debs.split(' ')) }}

COPY ["start.sh", "/usr/bin/"]
COPY ["profile.ini", "portmap.ini", "/etc/sai/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]

## Clean up
RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
RUN rm -rf /debs

ENTRYPOINT ["/usr/local/bin/supervisord"]