# docker image for docker-ptf-sai

DOCKER_PTF_SAI = docker-ptf-sai.gz
$(DOCKER_PTF_SAI)_PATH = $(PLATFORM_PATH)/docker-ptf
$(DOCKER_PTF_SAI)_DEPENDS += $(LIBTHRIFT_0_13_0) $(PYTHON3_THRIFT_0_13_0) $(PYTHON3_THRIFT_0_13_0) $(PTF) $(PYTHON_SAITHRIFT)
SONIC_DOCKER_IMAGES += $(DOCKER_PTF_SAI)

ifneq ($(ENABLE_SYNCD_RPC),y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_PTF_SAI)
endif